USE_GPU: False

ENV:
  NAME: "BreakoutDeterministic-v4"

TRAIN:
  TRAINER: "DQNTrainer"
  VERBOSE_INTERVAL: 1

DATASET:
  PIPELINES: ["TransformAtariInput", "ToTensor"]

LOGGER:
  LOG_FILE: True
  SAVE_MODEL: True
  SAVE_MODEL_INTERVAL: 100
  OUTPUT_DIR: "./work_dir/breakout_dqn_210907"
  LOG_NAME: "breakout_dqn_210907"
  