USE_GPU: True

TRAIN:
  TRAINER: "DDQNTrainer"
  NUM_EPISODES: 1000
  LEARNING_RATE: 0.0003
  BATCH_SIZE: 32
  VERBOSE_INTERVAL: 1
  TRAIN_INTERVAL: 1
  AVG_REWARDS_TO_TERMINATE: 1000

DATASET:
  USE_GPU: True

LOGGER:
  LOG_FILE: False
  SAVE_MODEL: False
  LOG_NAME: ""
  