NET:
  NAME: "ActionValueMLP"
  NUM_LAYERS: 1

ENV:
  MAX_EPISODE_STEPS: 1000

TRAIN:
  TRAINER: "QLearningTrainer"
  NUM_EPISODES: 10000
  DISCOUNT_RATE: 0.98
  VERBOSE_INTERVAL: 1
  HISTORY_SIZE: 10

OPTIMIZER:
  TYPE: "Adam"
  ARGS:
    lr: 0.003
    betas: (0.9, 0.999)

LOGGER:
  LOG_FILE: True
  SAVE_MODEL: False
  LOG_NAME: "cartpole_qlearning_210813"