NET:
  NAME: "MLP"
  NUM_LAYERS: 1

ENV:
  REWARD: 0.01
  REWARD_DONE: 0.0
  MAX_EPISODE_STEPS: 1000

TRAIN:
  TRAINER: "MCTrainer"
  NUM_EPISODES: 10000
  LEARNING_RATE: 0.003
  DISCOUNT_RATE: 0.98
  VERBOSE_INTERVAL: 1
  NUM_EPISIODES_AVG_STEPS: 10
  AVG_STEPS_TO_TERMINATE: 500
