NET:
  NAME: "ActionValueMLP"

TRAIN:
  TRAINER: "DDQNTrainer"
  VERBOSE_INTERVAL: 10
  TRAIN_INTERVAL: 1
  TARGET_SYNC_INTERVAL: 200
  NUM_ITERS_PER_TRAIN: 20

LOGGER:
  LOG_FILE: True
  SAVE_MODEL: True
  LOG_NAME: "cartpole_ddqn_210819"
  