NET:
  NAME: "ActionValueMLP"
  NUM_LAYERS: 1

ENV:
  MAX_EPISODE_STEPS: 1000

TRAIN:
  TRAINER: "SARSATrainer"
  NUM_EPISODES: 10000
  LEARNING_RATE: 0.003
  DISCOUNT_RATE: 0.98
  VERBOSE_INTERVAL: 1
  AVERAGE_SIZE: 10

LOGGER:
  LOG_FILE: True
  SAVE_MODEL: False
  LOG_NAME: "cartpole_sarsa_210813"