NET:
  NAME: "DuelingMLP"

TRAIN:
  TRAINER: "DDQNTrainer"
  NUM_EPISODES: 10000
  LEARNING_RATE: 0.0003
  BATCH_SIZE: 32
  DISCOUNT_RATE: 0.98
  VERBOSE_INTERVAL: 1
  TRAIN_INTERVAL: 1
  TARGET_SYNC_INTERVAL: 200
  NUM_ITERS_PER_TRAIN: 10

LOGGER:
  LOG_FILE: True
  SAVE_MODEL: True
  LOG_NAME: "cartpole_duelingdqn_210819"