NET:
  NAME: "ActionValueMLP"
  NUM_LAYERS: 1

ENV:
  MAX_EPISODE_STEPS: 1000

TRAIN:
  TRAINER: "SARSATrainer"
  NUM_EPISODES: 10000
  DISCOUNT_RATE: 0.98
  VERBOSE_INTERVAL: 1
  HISTORY_SIZE: 10

OPTIMIZER:
  ARGS:
    lr:  0.003

LOGGER:
  LOG_FILE: True
  SAVE_MODEL: False
  OUTPUT_DIR: "work_dir/cartpole_sarsa_210813"
  LOG_NAME: "cartpole_sarsa_210813"