NET:
  NAME: "ActorMLP"
  NUM_LAYERS: 2
  HIDDEN_DIM: 128

CRITIC:
  NAME: "CriticMLP"
  NUM_LAYERS: 2
  HIDDEN_DIM: 128

ENV:
  REWARD: 0.01
  REWARD_DONE: 0.0

TRAIN:
  TRAINER: "ActorCriticTrainer"
  NUM_EPISODES: 10000
  LEARNING_RATE: 0.0001
  BATCH_SIZE: 32
  DISCOUNT_RATE: 0.98
  VERBOSE_INTERVAL: 20
  TRAIN_INTERVAL: 1
  NUM_ITERS_PER_TRAIN: 1
  AVG_STEPS_TO_TERMINATE: 500

LOGGER:
  LOG_FILE: True
  SAVE_MODEL: False
  LOG_NAME: "cartpole_actor_critic_210813"
  