NET:
  NAME: "ActorCriticMLP"
  NUM_LAYERS: 2
  HIDDEN_DIM: 128

TRAIN:
  TRAINER: "ActorCriticTrainer"
  VERBOSE_INTERVAL: 20
  TRAIN_INTERVAL: 1
  NUM_ITERS_PER_TRAIN: 1

OPTIMIZER:
  CLIP_GRAD: True
  CLIP_GRAD_VALUE: 1.0
  
LOSS_FN:
  TYPE: "SmoothL1Loss"

LOGGER:
  LOG_FILE: False
  SAVE_MODEL: False
  LOG_NAME: "cartpole_actor_critic_210813"
  