NET:
  NAME: "ActionValueMLP"
  NUM_LAYERS: 1
  ACTION_DIM: 30
  STATE_DIM: 1000
  HIDDEN_DIM: 1000

ENV:
  NAME: "CustomersVisit-v0"
  MAX_EPISODE_STEPS: 100
  NUM_CONTENTS: 30
  NUM_CUSTOMERS: 1000
  NUM_OUTPUT: 1
  NUM_PREFERENCE: 2
  PROBABILITY: 1.0

TRAIN:
  TRAINER: "SARSATrainer"
  VERBOSE_INTERVAL: 10
  AVG_REWARDS_TO_TERMINATE: 99

OPTIMIZER:
  ARGS:
    lr: 0.001

LOGGER:
  LOG_FILE: True
  SAVE_MODEL: True
  LOG_TENSORBOARD: False
  SAVE_MODEL_INTERVAL: 500
  OUTPUT_DIR: "work_dir/customers_sarsa_211122"
  LOG_NAME: "customers_sarsa_211122"
  