NET:
  NAME: "ActionValueMLP"

TRAIN:
  TRAINER: "DDQNTrainer"
  TRAIN_BY_EPISODE: False
  START_TRAIN: 10000
  VERBOSE_INTERVAL: 1
  TRAIN_INTERVAL: 4
  TARGET_SYNC_INTERVAL: 20000
  NUM_ITERS_PER_TRAIN: 1

LOGGER:
  LOG_FILE: False
  SAVE_MODEL: False
  LOG_NAME: "cartpole_ddqn_210819"
  