from yacs.config import CfgNode as CN

_C = CN()

_C.NET = CN()
_C.NET.NAME = "ActionValueMLP"
_C.NET.NUM_LAYERS = 2
_C.NET.STATE_DIM = 4
_C.NET.HIDDEN_DIM = 128
_C.NET.ACTION_DIM = 2

_C.ENV = CN()
_C.ENV.NAME = "CartPole-v3"
_C.ENV.MAX_EPISODE_STEPS = 10000
_C.ENV.REWARD = 1.0
_C.ENV.REWARD_DONE = 0.0

_C.TRAIN = CN()
_C.TRAIN.TRAINER = ""
_C.TRAIN.LEARNING_RATE = 0.0003
_C.TRAIN.BATCH_SIZE = 32
_C.TRAIN.TRAIN_INTERVAL = 10
_C.TRAIN.NUM_ITERS_PER_TRAIN = 50
_C.TRAIN.DISCOUNT_RATE = 0.98
_C.TRAIN.NUM_EPISODES = 10000
_C.TRAIN.VERBOSE_INTERVAL = 10
_C.TRAIN.TARGET_SYNC_INTERVAL = 100
_C.TRAIN.NUM_EPISIODES_AVG_STEPS = 20
_C.TRAIN.AVG_STEPS_TO_TERMINATE = 5000
_C.TRAIN.EPISILON_GREEDY_MINMAX = (0.01, 0.08)

_C.LOGGER = CN()
_C.LOGGER.OUTPUT_DIR = "./output"
_C.LOGGER.LOG_NAME = ""
_C.LOGGER.LOG_FILE = False
_C.LOGGER.SAVE_MODEL = False

def get_cfg_defaults():
    return _C.clone()
